### PR TITLE
Avoid using Opt.auto to avoid overflows going silent

### LINKED ISSUE #860: Negative value overflows into positive in `create-protocol-parameters-update`
## Description

When creating pparam update proposal, negative value overflows into positive value.

## Steps to Reproduce

```shell
> cabal run cardano-cli -- conway stake-address key-gen --verification-key-file stake.vkey --signing-key-file stake.skey
> cardano-cli conway governance action create-protocol-parameters-update --testnet --governance-action-deposit 100000000 --deposit-return-stake-verification-key-file stake.vkey --anchor-url "http://www.pparam-action-wrtz.com/" --anchor-data-hash fb013f4b7ddb08fa20dd2974b8a4447598477886f544d71033da53390325cd37 --max-block-header-size -3161913232 --out-file pparams_update.action
> cardano-cli conway governance action view --action-file pparams_update.action
{
    "anchor": {
        "dataHash": "fb013f4b7ddb08fa20dd2974b8a4447598477886f544d71033da53390325cd37",
        "url": "http://www.pparam-action-wrtz.com"
    },
    "deposit": 100000000,
    "governance action": {
        "contents": [
            null,
            {
                "maxBlockHeaderSize": 2160
            },
            null
        ],
        "tag": "ParameterChange"
    },
    "return address": {
        "credential": {
            "keyHash": "7499af8367c8ae3ae72210e5e54525acd3b21c1560f97106446a674c"
        },
        "network": "Testnet"
    }
}
```

ie. `-3161913232` becomes `2160`.

## Additional Context

```
cardano-node 9.1.0 - linux-x86_64 - ghc-8.10
git rev 88293215da71e7284c0cd499d9fc1b9b1f9ce9a1

cardano-cli 9.2.1.0 - linux-x86_64 - ghc-8.10
git rev 88293215da71e7284c0cd499d9fc1b9b1f9ce9a1
```

### PR DESCRIPTION
**Pull request by smelc**
# Changelog

```yaml
- description: |
    Forbid incorrect values in parsers of many Int-like options. Previously those values would overflow and be turned into a random valid value. If this breaks your use case, this means your use case wasn't doing what you expected.
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
  # - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  # - refactoring    # QoL changes
  - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

We use [auto](https://hackage.haskell.org/package/optparse-applicative-0.18.1.0/docs/Options-Applicative.html#v:auto) a lot in parsing. `auto` relies under the hood on **Read** instances which are [known to have problems](https://github.com/NorfairKing/haskell-WAT#read-instances-for-integral-types). Some instances accept wrong values and return out of thin air values. This PR fixes this.

Fixes https://github.com/IntersectMBO/cardano-cli/issues/860

# How to trust this PR

* [X] Try this PR with `cardano-testnet`: tested `cabal test cardano-testnet-test` with `cardano-node` at e9ab511272a7694196778007211991a9984557e8 and `cardano-cli` at 44ca6edd1b3064ddf8f3bc155a8203188758cf14
* Run `git grep auto "*.hs"` and observe that all the remaining calls are in a `byron` file (I didn't change those)

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [x] New tests are added if needed and existing tests are updated. See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [x] Self-reviewed the diff

### CODE REVIEW

File: cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs [hunk 1]
```diff
@@ -3181,9 +3183,24 @@ pMaxTransactionSize =
...
+  -- We use 'readMaybe' instead of 'read', because the latter wouldn't output a nice error message
+  parser s =
+    case readMaybe s >>= naturalToWordMaybe >>= toIntegralSized of
+      Nothing ->
+        error $ "Cannot parse " <> s <> " as a " <> typeString
+      Just a ->
+        Just a
+
+word16Reader :: ReadM Word16
+word16Reader = wordReader @Word16 "Word16"
```
Comment (smelc) [inline cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs]: We could use fancy type-level stuff to avoid this `String` here, I know. Not my style though :slightly_smiling_face:

File: cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs [hunk 2]
```diff
@@ -3181,9 +3183,24 @@ pMaxTransactionSize =
...
 
+wordReader :: (Integral a, Bits a) => String -> ReadM a
+wordReader typeString =
+  Opt.maybeReader parser
+ where
+  -- We use 'readMaybe' instead of 'read', because the latter wouldn't output a nice error message
+  parser s =
+    case readMaybe s >>= naturalToWordMaybe >>= toIntegralSized of
+      Nothing ->
+        error $ "Cannot parse " <> s <> " as a " <> typeString
```
Comment (carbolymer) [inline cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs]: Why `error` and not `fail`?

File: cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs [hunk 3]
```diff
@@ -3181,9 +3183,24 @@ pMaxTransactionSize =
       , Opt.help "Maximum transaction size."
       ]
 
+wordReader :: (Integral a, Bits a) => String -> ReadM a
+wordReader typeString =
```
Comment (carbolymer) [inline cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs]:
```suggestion
wordReader typeName =
```
Can you add a comment highlighting that it tries to read the number and convert it to `Word`?

File: cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs (hunk 1 above)
Comment (carbolymer) [reply cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs]: What's wrong with `show $ typeRep (Proxy @a)` though? 😄

**Review by carbolymer — CHANGES_REQUESTED** [review]
I like the direction, but `wordReader` needs some polishing. 😃

File: cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs (hunk 1 above)
Comment (carbolymer) [reply cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs]: This type annotation is redundant here.

Comment (smelc) [reply cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs]: Nice, I didn't know it would be so easy, changed :+1:

File: cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs (hunk 2 above)
Comment (smelc) [reply cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs]: Because I didn't knew about `fail`.. Changed :+1:

File: cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs (hunk 3 above)
Comment (smelc) [reply cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs]: Done :+1:

**Comment by smelc** [comment]
@carbolymer> I did the changes :+1:

Given your last comment, I assume you're fine with me deploying this to many more code locations? (please don't approve though yet, because I'll extend this PR).

File: cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs [hunk 4]
```diff
@@ -3181,9 +3184,27 @@ pMaxTransactionSize =
...
+wordReader typeName =
+  Opt.maybeReader parser
+ where
+  -- We use 'readMaybe' instead of 'read', because the latter wouldn't output a nice error message
+  parser s =
+    case readMaybe s >>= naturalToWordMaybe >>= toIntegralSized of
+      Nothing ->
+        fail $ "Cannot parse " <> s <> " as a " <> typeName
+      Just a ->
+        Just a
```
Comment (carbolymer) [inline cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs]: what do you think about removing the function argument:
```suggestion
wordReader :: forall a. (Typeable a, Integral a, Bits a) => String -> ReadM a
wordReader =
  Opt.maybeReader parser
 where
  -- We use 'readMaybe' instead of 'read', because the latter wouldn't output a nice error message
  typeName = show $ typeRep (Proxy @a)
  parseFailure = fail $ "Cannot parse " <> s <> " as a " <> typeName
  parser s =
    fromMaybe parseFailure $
      readMaybe s >>= naturalToWordMaybe >>= toIntegralSized
```

Comment (carbolymer) [reply cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs]: Oh, I've just noticed the type `parser :: String -> Maybe a`. So I think you should use actually https://hackage.haskell.org/package/optparse-applicative-0.18.1.0/docs/src/Options.Applicative.Builder.html#eitherReader and return `Left` instead of `fail`.

Comment (smelc) [reply cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs]: @carbolymer> done changes:

1. Use `eitherReader`
2. Remove variable for type name

File: cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs [hunk 5]
```diff
@@ -3181,9 +3184,24 @@ pMaxTransactionSize =
       , Opt.help "Maximum transaction size."
       ]
 
+-- | @wordReader@ is a reader for a word of type @a@. When it fails
+-- parsing, it provides a nice error message. This custom reader is needed
+-- to avoid the overflow issues of 'Opt.auto' described in https://github.com/IntersectMBO/cardano-cli/issues/860.
+wordReader :: forall a. (Typeable a, Integral a, Bits a) => ReadM a
```
Comment (Jimbo4350) [inline cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs]: We should abandon `read` entirely. Have a look at `readerFromParsecParser` in `cardano-cli`.

**Review by Jimbo4350 — CHANGES_REQUESTED** [review]

File: cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs (hunk 5 above)
Comment (smelc) [reply cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs]: @Jimbo4350> I disagree: I think it's a bad idea to reinvent the wheel and write something like a `Parsec.Parser Word*`. It would be too error prone. I wouldn't trust myself and therefore I'd need a lot of tests.

I'd rather write tests for the implementation as it is now `readMaybe s >>= naturalToWordMaybe >>= toIntegralSized` (there are roundtripping properties here), if you are worried about incorrections.

Comment (carbolymer) [reply cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs]: I think what @Jimbo4350 meant is that we should use parsec to have more flexible number parsing. I think this way you'll avoid writing validation for the numbers from scratch (`naturalToWordMaybe >=> toIntegralSized` in your case) if you reuse already existing parsers from `parsec`. See [`parseLovelace`](https://github.com/IntersectMBO/cardano-cli/blob/aa389b09afaebf09403072a05b09dd69872a917c/cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs#L514) for example. 

See also: https://hackage.haskell.org/package/parsec-3.1.17.0/docs/Text-Parsec-Token.html#t:GenTokenParser

Comment (smelc) [reply cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs]: OK I see :+1: I did a `Parsec`-based implementation in the last commit.

Comment (Jimbo4350) [reply cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs]: A better name would be `integralReader`.

**Review by Jimbo4350 — COMMENTED** [review]
LGTM! Now just replace all calls to `auto`.

File: cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs (hunk 5 above)
Comment (smelc) [reply cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs]: Yep indeed :+1:

File: cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs [hunk 6]
```diff
@@ -3173,16 +3176,51 @@ pMaxBodySize =
...
       , Opt.metavar "WORD32"
       , Opt.help "Maximum transaction size."
       ]
 
+-- | A parser for @(Int, Int)@-like expressions. In other words, 'integralReader'-lifted
+-- to a pairs with a Haskell-like syntax.
+pairIntegralReader :: (Typeable a, Integral a, Bits a) => ReadM (a, a)
+pairIntegralReader = readerFromParsecParser pairIntegralParsecParser
+
+pairIntegralParsecParser :: (Typeable a, Integral a, Bits a) => Parsec.Parser (a, a)
```
Comment (smelc) [inline cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs:3191]: This one is important to review

**Review by CarlosLopezDeLara — APPROVED** [review]

File: cardano-cli/test/cardano-cli-test/Test/Cli/Parser.hs [hunk 7]
```diff
@@ -0,0 +1,66 @@
...
+  parse s =
+    case Parsec.runParser integralParsecParser () "" s of
+      Left parsecError -> Left $ show parsecError
+      Right x -> Right x
+
+-- | Execute me with:
+-- @cabal test cardano-cli-test --test-options '-p "/pair integral reader/"'@
+hprop_pair_integral_reader :: Property
+hprop_pair_integral_reader = propertyOnce $ do
+  assert $ isRight $ parse @Word "(0, 0)"
```
Comment (Jimbo4350) [inline cardano-cli/test/cardano-cli-test/Test/Cli/Parser.hs]: We can improve these tests with hedgehog generators. Example:
```diff
diff --git a/cardano-cli/test/cardano-cli-test/Test/Cli/Parser.hs b/cardano-cli/test/cardano-cli-test/Test/Cli/Parser.hs
index 1bf19f8b8..c72c8a093 100644
--- a/cardano-cli/test/cardano-cli-test/Test/Cli/Parser.hs
+++ b/cardano-cli/test/cardano-cli-test/Test/Cli/Parser.hs
@@ -1,3 +1,5 @@
+{-# LANGUAGE RankNTypes #-}
+{-# LANGUAGE ScopedTypeVariables #-}
 {-# LANGUAGE TypeApplications #-}
 
 module Test.Cli.Parser
@@ -12,11 +14,14 @@ import           Cardano.CLI.EraBased.Options.Common (integralParsecParser,
 import           Data.Bits (Bits)
 import           Data.Data (Typeable)
 import           Data.Either (isLeft, isRight)
+import           Data.Proxy
 import           Data.Word (Word16)
 import qualified Text.Parsec as Parsec
 
-import           Hedgehog (Property, assert)
+import           Hedgehog
 import           Hedgehog.Extras (propertyOnce)
+import qualified Hedgehog.Gen as Gen
+import qualified Hedgehog.Range as Range
 
 -- | Execute me with:
 -- @cabal test cardano-cli-test --test-options '-p "/integral reader/"'@
@@ -45,9 +50,8 @@ hprop_integral_reader = propertyOnce $ do
 -- @cabal test cardano-cli-test --test-options '-p "/pair integral reader/"'@
 hprop_pair_integral_reader :: Property
 hprop_pair_integral_reader = propertyOnce $ do
-  assert $ isRight $ parse @Word "(0, 0)"
-  assert $ isRight $ parse @Word "   (   0  ,   0   )"
-  assert $ isRight $ parse @Word " (18446744073709551615   ,    18446744073709551614   )   "
+  validArbitraryTuple <- forAll $ genNumberTuple (Proxy :: Proxy Word)
+  assert $ isRight $ parse @Word validArbitraryTuple
 
   assert $ isLeft $ parse @Word "(0, 0, 0)"
   assert $ isLeft $ parse @Word "(-1, 0)"
@@ -64,3 +68,18 @@ hprop_pair_integral_reader = propertyOnce $ do
     case Parsec.runParser pairIntegralParsecParser () "" s of
       Left parsecError -> Left $ show parsecError
       Right x -> Right x
+
+genNumberTuple
+  :: forall integral
+   . Integral integral
+  => Show integral
+  => Proxy integral -> Gen String
+genNumberTuple _ = do
+  x :: integral <- Gen.integral (Range.linear 0 100)
+  y :: integral <- Gen.integral (Range.linear 0 100)
+  space1 <- genArbitrarySpace
+  space2 <- genArbitrarySpace
+  return $ "(" ++ space2 ++ show x ++ space1 ++ "," ++ space2 ++ show y ++ space1 ++ ")"
+
+genArbitrarySpace :: Gen String
+genArbitrarySpace = Gen.string (Range.linear 0 5) (return ' ')

```

Comment (Jimbo4350) [reply cardano-cli/test/cardano-cli-test/Test/Cli/Parser.hs]: We should as much as possible avoid unit tests.

Comment (smelc) [reply cardano-cli/test/cardano-cli-test/Test/Cli/Parser.hs]: I took your suggestion and split the function into two, since the positive tests need to be run with `property`, while the negative tests need to run with `propertyOnce` :+1:

Comment (Jimbo4350) [reply cardano-cli/test/cardano-cli-test/Test/Cli/Parser.hs]: > while the negative tests need to run with propertyOnce


Why? You could also write a generator to inject a random character (or multiple characters) between the brackets for the negative tests.

File: cardano-cli/test/cardano-cli-test/Test/Cli/Parser.hs [hunk 8]
```diff
@@ -0,0 +1,105 @@
...
+import           Hedgehog.Extras (propertyOnce)
+import qualified Hedgehog.Gen as Gen
+import           Hedgehog.Internal.Property (forAll)
+import qualified Hedgehog.Range as Range
+
+-- | Execute me with:
+-- @cabal test cardano-cli-test --test-options '-p "/integral reader/"'@
+hprop_integral_reader :: Property
+hprop_integral_reader = propertyOnce $ do
+  assert $ isRight $ parse @Word "0"
```
Comment (Jimbo4350) [inline cardano-cli/test/cardano-cli-test/Test/Cli/Parser.hs]: You should use https://hackage.haskell.org/package/hedgehog-1.5/docs/Hedgehog-Internal-Gen.html#v:word instead.

File: cardano-cli/test/cardano-cli-test/Test/Cli/Parser.hs [hunk 9]
```diff
@@ -0,0 +1,105 @@
...
+      Right x -> Right x
+
+-- | Execute me with:
+-- @cabal test cardano-cli-test --test-options '-p "/integral pair reader positive/"'@
+hprop_integral_pair_reader_positive :: Property
+hprop_integral_pair_reader_positive = property $ do
+  validArbitraryTuple <- forAll $ genNumberTuple (Proxy :: Proxy Word)
+  assert $ isRight $ parse @Word validArbitraryTuple
+
+  assert $ isLeft $ parse @Word "(0, 0, 0)"
```
Comment (Jimbo4350) [inline cardano-cli/test/cardano-cli-test/Test/Cli/Parser.hs]: You can write a generator that injects a random character (or characters) into the string generated by `genNumberTuple`. This would provide better coverage.

File: cardano-cli/test/cardano-cli-test/Test/Cli/Parser.hs [hunk 10]
```diff
@@ -0,0 +1,105 @@
...
+  assert $ isLeft $ parse @Word "(-1, 0)"
+  assert $ isLeft $ parse @Word "(18446744073709551616, 0)"
+  assert $ isLeft $ parse @Word "(0, 18446744073709551616)"
```
Comment (Jimbo4350) [inline cardano-cli/test/cardano-cli-test/Test/Cli/Parser.hs]: These are already tested in `hprop_integral_pair_reader_negative`

**Review by Jimbo4350 — APPROVED** [review]
LGTM however you can improve your tests further using hedgehog generators.

File: cardano-cli/test/cardano-cli-test/Test/Cli/Parser.hs (hunk 10 above)
Comment (smelc) [reply cardano-cli/test/cardano-cli-test/Test/Cli/Parser.hs]: Ooops, good catch. Correcting :+1:

File: cardano-cli/test/cardano-cli-test/Test/Cli/Parser.hs (hunk 7 above)
Comment (smelc) [reply cardano-cli/test/cardano-cli-test/Test/Cli/Parser.hs]: Yes but I would need to rule out generators that would still yield a valid value (e.g. if the generated character is a number) and I believe writing a good generator for negative tests it overkill for testing this parser. So I'll stick to the manual negative tests to speed up merging.

File: cardano-cli/test/cardano-cli-test/Test/Cli/Parser.hs (hunk 8 above)
Comment (smelc) [reply cardano-cli/test/cardano-cli-test/Test/Cli/Parser.hs]: :+1: Done with:

```haskell
  w <- forAll $ Gen.word $ Gen.linear minBound maxBound
  assert $ isRight $ parse @Word (show w)
```

File: cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs (hunk 6 above)
Comment (carbolymer) [reply cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs:3191]: looks fine to me 👌🏻

File: cardano-cli/test/cardano-cli-test/Test/Cli/Parser.hs [hunk 11]
```diff
@@ -0,0 +1,99 @@
...
+import           Hedgehog.Internal.Property (forAll)
+import qualified Hedgehog.Range as Gen
+import qualified Hedgehog.Range as Range
+
+-- | Execute me with:
+-- @cabal test cardano-cli-test --test-options '-p "/integral reader/"'@
+hprop_integral_reader :: Property
+hprop_integral_reader = property $ do
+  assert $ isRight $ parse @Word "0"
+  assert $ isRight $ parse @Word "42"
```
Comment (carbolymer) [inline cardano-cli/test/cardano-cli-test/Test/Cli/Parser.hs]: it would be better to check the exact value in case of `Right`s here
```suggestion
parse @Word "42" === Right 42
```

File: cardano-cli/test/cardano-cli-test/Test/Cli/Parser.hs [hunk 12]
```diff
@@ -0,0 +1,99 @@
...
+  assert $ isLeft $ parse @Word "-1"
+  assert $ isLeft $ parse @Word "18446744073709551616"
```
Comment (carbolymer) [inline cardano-cli/test/cardano-cli-test/Test/Cli/Parser.hs]: It would be better to write this as
```suggestion
  assertWith isLeft $ parse @Word "18446744073709551616"
```
`assert` does not report the value on assertion failure

**Review by carbolymer — APPROVED** [review]
LGTM

File: cardano-cli/test/cardano-cli-test/Test/Cli/Parser.hs (hunk 11 above)
Comment (smelc) [reply cardano-cli/test/cardano-cli-test/Test/Cli/Parser.hs]: Good point, changing :+1:

File: cardano-cli/test/cardano-cli-test/Test/Cli/Parser.hs (hunk 12 above)
Comment (smelc) [reply cardano-cli/test/cardano-cli-test/Test/Cli/Parser.hs]: Changed to (for example) `assertWith (parse @Word "18446744073709551616") isLeft`
