### PR TITLE
verification-key: support DRep keys as well as committee keys, extended or not

### LINKED ISSUE #651: cardano-cli `conway key verification-key` command does not support DRep, CC-Cold & CC-Hot signing keys
```console
$ cardano-cli version
cardano-cli 8.20.3.0 - linux-x86_64 - ghc-8.10
git rev 0d98405a60d57e1c8e13406d51cce0e34356bd64
```
---

```json
drep.skey
{
    "type": "DRepSigningKey_ed25519",
    "description": "Delegate Representative Signing Key",
    "cborHex": "5820bc9140f07f94782afd33b27b396f32678277d720166e1c48fd83eb8d1d6f8f17"
}
```

```console
$ cardano-cli conway key verification-key --signing-key-file drep.skey --verification-key-file /dev/stdout
```
> Command failed: key verification-key  Error: mydrep4.drep.skey: TextEnvelope type error:  Expected one of: PaymentSigningKeyByron_ed25519_bip32, PaymentSigningKeyShelley_ed25519, PaymentExtendedSigningKeyShelley_ed25519_bip32, StakeSigningKeyShelley_ed25519, StakeExtendedSigningKeyShelley_ed25519_bip32, StakePoolSigningKey_ed25519, GenesisSigningKey_ed25519, GenesisExtendedSigningKey_ed25519_bip32, GenesisDelegateSigningKey_ed25519, GenesisDelegateExtendedSigningKey_ed25519_bip32, GenesisUTxOSigningKey_ed25519, VrfSigningKey_PraosVRF, KesSigningKey_ed25519_kes_2^6 Actual: DRepSigningKey_ed25519

---
```json
drep-extended.skey
{
  "type": "DRepExtendedSigningKey_ed25519_bip32",
  "description": "Delegate Representative Signing Key",
  "cborHex": "588048b9578fe1a8fde546fcf5c134a7928b5213f3c2d49766becea5e3078a96354fb3ab263592401d61853957110a688cac3137649efba52994153fb6fd6b29c585b18eacea2003b68e39137545e9d42ce5bca133ca0334d6a75aa9cb1fd02be7ec90e91f5357e2c68949f0f09717c5b9809b6a74d5f87ea35383c82841f2357564"
}
```

```console
$ cardano-cli conway key verification-key --signing-key-file drep-extended.skey --verification-key-file /dev/stdout
```
> Command failed: key verification-key  Error: mydrep.drep.skey: TextEnvelope type error:  Expected one of: PaymentSigningKeyByron_ed25519_bip32, PaymentSigningKeyShelley_ed25519, PaymentExtendedSigningKeyShelley_ed25519_bip32, StakeSigningKeyShelley_ed25519, StakeExtendedSigningKeyShelley_ed25519_bip32, StakePoolSigningKey_ed25519, GenesisSigningKey_ed25519, GenesisExtendedSigningKey_ed25519_bip32, GenesisDelegateSigningKey_ed25519, GenesisDelegateExtendedSigningKey_ed25519_bip32, GenesisUTxOSigningKey_ed25519, VrfSigningKey_PraosVRF, KesSigningKey_ed25519_kes_2^6 Actual: DRepExtendedSigningKey_ed25519_bip32

---

⚠️Same goes with all variations of the Committee-Cold and Committee-Hot signing keys (normal and extended)!

### PR DESCRIPTION
**Pull request by smelc**
# Changelog

```yaml
- description: |
    verification-key: support DRep keys as well as committee keys, extended or not
# uncomment types applicable to the change:
  type:
  - feature        # introduces a new feature
  # - breaking       # the API has changed in a breaking way
  - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  # - improvement    # QoL changes e.g. refactoring
  - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

Fixes https://github.com/IntersectMBO/cardano-cli/issues/651

# How to trust this PR

* Run the new tests before the PR, witness the tests don't pass
* Run the new tests on the PR's head, witness the tests pass

# Checklist

- [X] Commit sequence broadly makes sense and commits have useful messages
- [X] New tests are added if needed and existing tests are updated. See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [X] Self-reviewed the diff

### CODE REVIEW

File: cardano-cli/src/Cardano/CLI/Read.hs [hunk 1]
```diff
@@ -721,6 +721,8 @@ readWitnessSigningData (KeyWitnessSigningData skFile mbByronAddr) = do
           -- A Byron address should only be specified along with a Byron signing key.
           Left ReadWitnessSigningDataSigningKeyAndAddressMismatch
   where
+    -- If you update these variables, consider updating the ones with the same
+    -- names in Cardano.CLI.Read
```
Comment (carbolymer) [inline cardano-cli/src/Cardano/CLI/Read.hs]: This comment is confusing - it's `Cardano.CLI.Read` module. Copy & paste error?

File: cardano-cli/test/cardano-cli-golden/Test/Golden/Governance/Committee.hs [hunk 2]
```diff
@@ -207,17 +216,42 @@ hprop_golden_governance_committee_cold_extended_key_signing =
...
+                 )
+               ]
+
+  propertyOnce $ forM_ values $ \(semaphore, vkeyGolden) ->
+    H.moduleWorkspace "tmp" $ \tempDir -> do
+      vkeyFileOut <- noteTempFile tempDir "cc.extended.vkey"
+
+      H.noteM_ $ bracketSem semaphore $ \skeyFile -> execCardanoCLI
+        [  "conway", "key", "verification-key"
+        , "--signing-key-file", skeyFile
```
Comment (carbolymer) [inline cardano-cli/test/cardano-cli-golden/Test/Golden/Governance/Committee.hs:244]: You don't need a semaphore for the signing key. It's used as an input here (only read), so protecting it seems redundant.

File: cardano-cli/test/cardano-cli-golden/Test/Golden/Governance/Committee.hs [hunk 3]
```diff
@@ -187,13 +196,13 @@ hprop_golden_governanceUpdateCommittee =
...
   propertyOnce . H.moduleWorkspace "tmp" $ \tempDir -> do
-    skeyFile <- noteInputFile "test/cardano-cli-golden/files/input/governance/committee/cc.extended.cold.skey"
+    void $ noteInputFile "test/cardano-cli-golden/files/input/governance/committee/cc.extended.cold.skey"
     txBody <- noteInputFile "test/cardano-cli-golden/files/input/governance/drep/extended-key-signing/tx.body"
 
     outGold <- H.note "test/cardano-cli-golden/files/golden/governance/committee/tx.cold.extended.signed"
     outFile <- H.noteTempFile tempDir "outFile"
 
-    H.noteM_ $ execCardanoCLI
+    H.noteM_ $ bracketSem extendedColdCCSkeySem $ \skeyFile -> execCardanoCLI
```
Comment (carbolymer) [inline cardano-cli/test/cardano-cli-golden/Test/Golden/Governance/Committee.hs]: Semaphore for input file (which is only read) seems redundant here.

File: cardano-cli/test/cardano-cli-golden/Test/Golden/Governance/DRep.hs [hunk 4]
```diff
@@ -99,13 +105,12 @@ hprop_golden_governance_drep_id_hex =
...
 hprop_golden_governance_drep_extended_key_signing =
   propertyOnce . H.moduleWorkspace "tmp" $ \tempDir -> do
-    skeyFile <- noteInputFile "test/cardano-cli-golden/files/input/governance/drep/extended-key-signing/drep.skey"
     txBody <- noteInputFile "test/cardano-cli-golden/files/input/governance/drep/extended-key-signing/tx.body"
 
     outFile <- H.noteTempFile tempDir "outFile"
     outGold <- H.note "test/cardano-cli-golden/files/golden/governance/drep/extended-key-signing/tx.signed"
 
-    void $ execCardanoCLI
+    H.noteShowM_ $ bracketSem extendedDRepSkeySem $ \skeyFile -> execCardanoCLI
```
Comment (carbolymer) [inline cardano-cli/test/cardano-cli-golden/Test/Golden/Governance/DRep.hs]: Semaphore for an input key (which is only read here) seems redundant

File: cardano-cli/test/cardano-cli-golden/Test/Golden/Governance/DRep.hs [hunk 5]
```diff
@@ -276,3 +281,19 @@ hprop_golden_governance_drep_update_certificate_vkey_file = propertyOnce . H.mod
...
+
+-- | Execute me with:
+-- @cabal test cardano-cli-golden --test-options '-p "/golden verification key drep/"'@
+hprop_golden_verification_key_drep :: Property
+hprop_golden_verification_key_drep =
+  propertyOnce . H.moduleWorkspace "tmp" $ \tempDir -> do
+      vkeyFileOut <- noteTempFile tempDir "drep.extended.vkey"
+      goldenFile <- H.note "cardano-cli/test/cardano-cli-golden/files/golden/governance/drep/drep-extended.vkey.out"
+
+      H.noteShowM_ $ bracketSem extendedDRepSkeySem $ \skeyFile -> execCardanoCLI
```
Comment (carbolymer) [inline cardano-cli/test/cardano-cli-golden/Test/Golden/Governance/DRep.hs]: The same case - semaphore for input file is redundant.

File: cardano-cli/test/cardano-cli-test-lib/Test/Cardano/CLI/Aeson.hs [hunk 6]
```diff
@@ -118,3 +121,43 @@ assertHasMapping file obj key value = GHC.withFrozenCallStack $ do
...
+      return $ Object $ Aeson.KeyMap.delete (Aeson.fromText "description") inner
+    Array _  -> failWrongType "array"
+    Number _ -> failWrongType "number"
+    Bool _   -> failWrongType "bool"
+    String _ -> failWrongType "string"
+    Null     -> failWrongType "null"
+   where
+     failWrongType got = do
+       H.note_ $ "Expected object but got: " <> got
+       H.failure
```
Comment (carbolymer) [inline cardano-cli/test/cardano-cli-test-lib/Test/Cardano/CLI/Aeson.hs:163]: What do you think about using [`lens-aeson`](https://hackage.haskell.org/package/lens-aeson-1.2.3/docs/Data-Aeson-Lens.html#v:atKey) here?
```suggestion
  v & L.atKey "description" .~ Nothing
```
Matching on `Value` constructors seems a bit excessive here.

File: cardano-cli/test/cardano-cli-test/Test/Cli/VerificationKey.hs [hunk 7]
```diff
@@ -0,0 +1,57 @@
...
+hprop_verification_key_committee_cold =
+  propertyOnce . H.moduleWorkspace "tmp" $ runOne ["committee", "key-gen-cold"]
+
+runOne :: ()
+  => (HasCallStack, MonadCatch m, MonadIO m, MonadTest m)
+  => [String] -- ^ The piece of the command to generate the keys
+  -> FilePath -- ^ The temporary directory, i.e. where the test is allowed to generate files
+  -> m ()
+runOne cmd tempDir = GHC.withFrozenCallStack $ do
+    verificationKeyFile    <- noteTempFile tempDir "gen.vkey"
```
Comment (carbolymer) [inline cardano-cli/test/cardano-cli-test/Test/Cli/VerificationKey.hs]: Overindented, it should be 2 spaces

**Review by carbolymer — APPROVED** [review]
Nice work.

File: cardano-cli/src/Cardano/CLI/Read.hs (hunk 1 above)
Comment (smelc) [reply cardano-cli/src/Cardano/CLI/Read.hs]: Yep, copy/paste error. good catch! Corrected :+1:

File: cardano-cli/test/cardano-cli-test-lib/Test/Cardano/CLI/Aeson.hs (hunk 6 above)
Comment (smelc) [reply cardano-cli/test/cardano-cli-test-lib/Test/Cardano/CLI/Aeson.hs:163]: Do I assume right that the lens will not fail if the `Value` is not an `Object`? (it will simply do nothing)

That's just for me to know, behavior is fine for me in this case.

File: cardano-cli/test/cardano-cli-test/Test/Cli/VerificationKey.hs (hunk 7 above)
Comment (smelc) [reply cardano-cli/test/cardano-cli-test/Test/Cli/VerificationKey.hs]: Changed :+1:

File: cardano-cli/test/cardano-cli-golden/Test/Golden/Governance/Committee.hs (hunk 2 above)
Comment (smelc) [reply cardano-cli/test/cardano-cli-golden/Test/Golden/Governance/Committee.hs:244]: Changed :+1:

File: cardano-cli/test/cardano-cli-golden/Test/Golden/Governance/Committee.hs (hunk 3 above)
Comment (smelc) [reply cardano-cli/test/cardano-cli-golden/Test/Golden/Governance/Committee.hs]: Changed :+1:

File: cardano-cli/test/cardano-cli-test-lib/Test/Cardano/CLI/Aeson.hs (hunk 6 above)
Comment (carbolymer) [reply cardano-cli/test/cardano-cli-test-lib/Test/Cardano/CLI/Aeson.hs:163]: I think so. That's how I understand the signature. Something similar to [`alter`](https://hackage.haskell.org/package/containers-0.7/docs/Data-Map-Internal.html#v:alter).

Comment (smelc) [reply cardano-cli/test/cardano-cli-test-lib/Test/Cardano/CLI/Aeson.hs:163]: @carbolymer> this would be the first time we use `lens` and `lens-aeson` in this repo, which I'm not comfortable to add myself. It's quite something we are pulling here, so I rather keep my lowtech initial version.

File: cardano-cli/test/cardano-cli-golden/Test/Golden/Governance/DRep.hs (hunk 4 above)
Comment (smelc) [reply cardano-cli/test/cardano-cli-golden/Test/Golden/Governance/DRep.hs]: Good catch, semaphore is only needed for concurrent writes, so not for input files, only golden ones!

File: cardano-cli/test/cardano-cli-golden/Test/Golden/Governance/DRep.hs (hunk 5 above)
Comment (smelc) [reply cardano-cli/test/cardano-cli-golden/Test/Golden/Governance/DRep.hs]: Changed :+1:
