### PR TITLE
Fix inversion in --include-stake parser + print "stake" field even when there is no stake (do not hide stake absence)

### LINKED ISSUE #623: cardano-cli `query drep-state` issues with `--include-stake`
```console
$ ./cardano-cli-latest version
cardano-cli 8.20.1.0 - linux-x86_64 - ghc-8.10
git rev 7f49f394d364f8a0b6533051114a63a54cd47a81
```

Doing a query for a specific `--drep-key-hash` does not return the stake even if the flag `--include-stake` is set:

```console
$ ./cardano-cli-latest conway query drep-state --drep-key-hash 7fb3e519ac284cd198e8e403d97b5b3ff58aa798ef85faf39d95971b --include-stake
```
```json
[
    [
        {
            "keyHash": "7fb3e519ac284cd198e8e403d97b5b3ff58aa798ef85faf39d95971b"
        },
        {
            "anchor": null,
            "deposit": 2000000,
            "expiry": 269
        }
    ]
]
```

However, doing a query for `--all-dreps` not only autoincludes(should be off by default) the stake query but when you look at the data for the example drep-key-hash above the output is:
```console
$ ./cardano-cli-latest conway query drep-state --all-dreps
```
```json
...
[
        {
            "keyHash": "7fb3e519ac284cd198e8e403d97b5b3ff58aa798ef85faf39d95971b"
        },
        {
            "anchor": null,
            "deposit": 2000000,
            "expiry": 269,
            "stake": 37992188702
        }
    ],
...
```

@carlhammann @smelc

### PR DESCRIPTION
**Pull request by smelc**
# Changelog

```yaml
- description: |
    Fixed `--include-stake` behavior in `query drep-state`
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
  - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  # - improvement    # QoL changes e.g. refactoring
  - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

Fixes https://github.com/IntersectMBO/cardano-cli/issues/623

# How to trust this PR

I've tested the behavior of this PR on this branch of `cardano-node`: see the HEAD of https://github.com/IntersectMBO/cardano-node/commits/smelc/test-of-cli-pull-698/

# Checklist

- [X] Commit sequence broadly makes sense and commits have useful messages
- NA New tests are added if needed and existing tests are updated. See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [X] Self-reviewed the diff

### CODE REVIEW

File: cardano-cli/src/Cardano/CLI/EraBased/Run/Query.hs [hunk 1]
```diff
@@ -1501,19 +1499,20 @@
...
+      -> (L.Credential L.DRepRole StandardCrypto, L.DRepState StandardCrypto)
+      -> (L.Credential L.DRepRole StandardCrypto, A.Value)
+    drepStateToJson stakeDistr (cred, ds) = (cred, A.object $
+      [ "expiry" .= (ds ^. L.drepExpiryL)
+      , "anchor" .= (ds ^. L.drepAnchorL)
+      , "deposit" .= (ds ^. L.drepDepositL)
+      ] <>
+        (if includeStakeBoolean
+         then [ "stake" .= Map.lookup (L.DRepCredential cred) stakeDistr ]
+         else []))
```
[the remark this answers is not in the document]
Comment (smelc) [reply cardano-cli/src/Cardano/CLI/EraBased/Run/Query.hs]: Changed :+1:

File: cardano-cli/src/Cardano/CLI/EraBased/Options/Query.hs [hunk 2]
```diff
@@ -364,14 +364,14 @@ pQueryDRepStateCmd era envCli = do
         <$> pSocketPath envCli
         <*> pConsensusModeParams
         <*> pNetworkId envCli
-        <*> pAllOrOnlyDRepHashSoure
-        <*> Opt.flag WithStake NoStake (mconcat
+        <*> pAllOrOnlyDRepHashSource
+        <*> Opt.flag NoStake WithStake (mconcat
```
Comment (smelc) [inline cardano-cli/src/Cardano/CLI/EraBased/Options/Query.hs:368]: This is one of the two important bits of this PR: the arguments to [Opt.flag](https://hackage.haskell.org/package/optparse-applicative-0.18.1.0/docs/Options-Applicative.html#v:flag) are as follows:

1. The default value
2. The modified value

Here the two values were inverted. This change fixes that.

File: cardano-cli/src/Cardano/CLI/EraBased/Run/Query.hs [hunk 3]
```diff
@@ -1501,19 +1500,20 @@ runQueryDRepState
...
+      => ToJSON a
+      => Map (L.DRep StandardCrypto) a
+      -> (L.Credential L.DRepRole StandardCrypto, L.DRepState StandardCrypto)
+      -> (L.Credential L.DRepRole StandardCrypto, A.Value)
+    drepStateToJson stakeDistr (cred, ds) = (cred, A.object $
+      [ "expiry" .= (ds ^. L.drepExpiryL)
+      , "anchor" .= (ds ^. L.drepAnchorL)
+      , "deposit" .= (ds ^. L.drepDepositL)
+      ] <>
+        (if includeStakeBoolean
```
Comment (smelc) [inline cardano-cli/src/Cardano/CLI/EraBased/Run/Query.hs]: This is the other important bit of this PR: we want to condition the presence of the `stake` field on the value passed to the parser, not on the presence of stake in the data; because if there no stake, the `stake` field will get omitted.

After this PR, if there is no stake delegated to the concerned DRep, the `stake` field will be present and set to `null`; which is a better behavior IMHO.

Comment (Jimbo4350) [reply cardano-cli/src/Cardano/CLI/EraBased/Run/Query.hs]: You can `case` on `includeStake` instead of converting to a `Bool`.

**Review by Jimbo4350 — APPROVED** [review]
LGTM! One minor comment.

File: cardano-cli/src/Cardano/CLI/EraBased/Run/Query.hs (hunk 3 above)
Comment (smelc) [reply cardano-cli/src/Cardano/CLI/EraBased/Run/Query.hs]: Good point :+1: Done :bow:
