### PR TITLE
query protocol-parameters: use ledger JSON encoding, not API one

### LINKED ISSUE #729: query protocol-parameters does not show params introduced in Conway
## Description

We are missing the parameters introduced in conway in the output of `query protocol-parameters`
```
cardano-cli conway query protocol-parameters 
{
    "collateralPercentage": 150,
    "costModels": {
        "PlutusV1": [
        ],
        "PlutusV2": [
        ]
    },
    "decentralization": null,
    "executionUnitPrices": {
        "priceMemory": 5.77e-2,
        "priceSteps": 7.21e-5
    },
    "extraPraosEntropy": null,
    "maxBlockBodySize": 90112,
    "maxBlockExecutionUnits": {
        "memory": 62000000,
        "steps": 20000000000
    },
    "maxBlockHeaderSize": 1100,
    "maxCollateralInputs": 3,
    "maxTxExecutionUnits": {
        "memory": 14000000,
        "steps": 10000000000
    },
    "maxTxSize": 16384,
    "maxValueSize": 5000,
    "minPoolCost": 340000000,
    "minUTxOValue": null,
    "monetaryExpansion": 3.0e-3,
    "poolPledgeInfluence": 0.3,
    "poolRetireMaxEpoch": 18,
    "protocolVersion": {
        "major": 9,
        "minor": 0
    },
    "stakeAddressDeposit": 2000000,
    "stakePoolDeposit": 500000000,
    "stakePoolTargetNum": 500,
    "treasuryCut": 0.2,
    "txFeeFixed": 155381,
    "txFeePerByte": 44,
    "utxoCostPerByte": 4310
```
## Desired behavior

`query protocol parameters` output should be similar to 

``` 
cardano-cli conway query gov-state | jq .currentPParams
{
  "collateralPercentage": 150,
  "committeeMaxTermLength": 73,
  "committeeMinSize": 7,
  "costModels": {
    "PlutusV1": [
    ],
    "PlutusV2": [
    ]
  },
  "dRepActivity": 20,
  "dRepDeposit": 500000000,
  "dRepVotingThresholds": {
    "committeeNoConfidence": 0.6,
    "committeeNormal": 0.67,
    "hardForkInitiation": 0.6,
    "motionNoConfidence": 0.67,
    "ppEconomicGroup": 0.67,
    "ppGovGroup": 0.75,
    "ppNetworkGroup": 0.67,
    "ppTechnicalGroup": 0.67,
    "treasuryWithdrawal": 0.67,
    "updateToConstitution": 0.75
  },
  "executionUnitPrices": {
    "priceMemory": 0.0577,
    "priceSteps": 7.21e-05
  },
  "govActionDeposit": 50000000000,
  "govActionLifetime": 6,
  "maxBlockBodySize": 90112,
  "maxBlockExecutionUnits": {
    "memory": 62000000,
    "steps": 20000000000
  },
  "maxBlockHeaderSize": 1100,
  "maxCollateralInputs": 3,
  "maxTxExecutionUnits": {
    "memory": 14000000,
    "steps": 10000000000
  },
  "maxTxSize": 16384,
  "maxValueSize": 5000,
  "minFeeRefScriptCostPerByte": 44,
  "minPoolCost": 340000000,
  "monetaryExpansion": 0.003,
  "poolPledgeInfluence": 0.3,
  "poolRetireMaxEpoch": 18,
  "poolVotingThresholds": {
    "committeeNoConfidence": 0.51,
    "committeeNormal": 0.6,
    "hardForkInitiation": 0.51,
    "motionNoConfidence": 0.6,
    "ppSecurityGroup": 0.6
  },
  "protocolVersion": {
    "major": 9,
    "minor": 0
  },
  "stakeAddressDeposit": 2000000,
  "stakePoolDeposit": 500000000,
  "stakePoolTargetNum": 500,
  "treasuryCut": 0.2,
  "txFeeFixed": 155381,
  "txFeePerByte": 44,
  "utxoCostPerByte": 4310
}
```

## Steps to Reproduce

1. Connect to SanchoNet or a local cluster running Conway era
2. query the protocol parameters with `cardano-cli conway query protocol-parameters ` 
3. the output only includes pre-conway era prototol parameters 

## Possible Solution

We need to return all parameters.

### PR DESCRIPTION
**Pull request by smelc**
# Changelog

```yaml
- description: |
    query protocol-parameters: use ledger JSON encoding, not API one
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
  - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  # - refactoring    # QoL changes
  # - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

* Fixes https://github.com/IntersectMBO/cardano-cli/issues/729
* Result looked at by @gitmachtl already

# How to trust this PR

* `cardano-node`'s tests ran on this PR: https://github.com/IntersectMBO/cardano-node/pull/5839
* Review the diff of golden files on `cardano-node`'s PR: https://github.com/IntersectMBO/cardano-node/pull/5839/files

# Checklist

- [X] Commit sequence broadly makes sense and commits have useful messages
- [X] Self-reviewed the diff

### CODE REVIEW

File: cardano-cli/src/Cardano/CLI/EraBased/Run/Query.hs [hunk 1]
```diff
@@ -177,15 +177,16 @@ runQueryProtocolParametersCmd
...
       :: ShelleyBasedEra era
       -> Maybe (File () Out)
       -> L.PParams (ShelleyLedgerEra era)
       -> ExceptT QueryCmdError IO ()
     writeProtocolParameters sbe mOutFile' pparams =
       firstExceptT QueryCmdWriteFileError . newExceptT
-        $ writeLazyByteStringOutput mOutFile' $ encodePretty $ fromLedgerPParams sbe pparams
+        $ writeLazyByteStringOutput mOutFile'
+          $ shelleyBasedEraConstraints sbe
+            $ encodePretty pparams
```
Comment (carbolymer) [inline cardano-cli/src/Cardano/CLI/EraBased/Run/Query.hs:189]: What about this TODO: https://github.com/IntersectMBO/cardano-cli/blob/main/cardano-cli/src/Cardano/CLI/EraBased/Run/Transaction.hs#L506
Are we able to round-trip i.e. read the parameters into the `transaction build` after your change? Afair there was a testnet test for that.

Comment (smelc) [reply cardano-cli/src/Cardano/CLI/EraBased/Run/Query.hs:189]: Notes to myself:

* On one hand, `transaction build` doesn't read the parameters by using the CLI's code: it requests them from the node
* On the other hand, `transaction build-raw` does read parameters from the command line.

Comment (smelc) [reply cardano-cli/src/Cardano/CLI/EraBased/Run/Query.hs:189]: @carbolymer> actually there are multiple usages of the API JSON encoding:

1. In `build-estimate`: https://github.com/IntersectMBO/cardano-cli/blob/main/cardano-cli/src/Cardano/CLI/EraBased/Run/Transaction.hs#L286
2. In `build-raw` (the one you pointed out)
3. In `calculate-min-fee`: https://github.com/IntersectMBO/cardano-cli/blob/main/cardano-cli/src/Cardano/CLI/EraBased/Run/Transaction.hs#L1261
4. In `calculate-min-value`: https://github.com/IntersectMBO/cardano-cli/blob/main/cardano-cli/src/Cardano/CLI/EraBased/Run/Transaction.hs#L1342

Should we change all of them?

@gitmachtl> would you be able to test this change before we merge it? I'm afraid we are not the best ones to test this change exhaustively.

Comment (gitmachtl) [reply cardano-cli/src/Cardano/CLI/EraBased/Run/Query.hs:189]: sure, also those are really important. let me compile the cli for testing...

Comment (gitmachtl) [reply cardano-cli/src/Cardano/CLI/EraBased/Run/Query.hs:189]: @smelc so first issue i see is, that cli is complaining about the missing parameter `key "minUTxOValue" not found`

so the parameters with `null` value that were sorted out are causing an issue here. cli expects at least that the key is in there.

afaik only those parameters are automatically "trimmed" out right now:
```json
    "decentralization": null,
    "extraPraosEntropy": null,
    "minUTxOValue": null,
```

not sure if "decentralization" and "extraPraosEntropy" are actually ever read back for some processes? if not, only the "minUTxoValue" one is an issue. that parameter was only used pre babbage era, so would it be an option to only read that in if the used era expects it? `utxoCostPerWord` is also not present anymore in latest eras. but was used before, that might also be an issue during bootstrap phase to get thru the eras.

Comment (smelc) [reply cardano-cli/src/Cardano/CLI/EraBased/Run/Query.hs:189]: @gitmachtl> is there a way I can reproduce your tests myself? So that then I can investigate how to fix the issues in autonomy.

Comment (gitmachtl) [reply cardano-cli/src/Cardano/CLI/EraBased/Run/Query.hs:189]: @smelc Sure, you can simply copy&paste those lines on the cli.

```bash
dummyTx='{"type":"Unwitnessed Tx ConwayEra","description":"Ledger Cddl Format","cborHex":"84a400d901028182582090ebfd31ec657d52eecf489871ecabefdce3753877aee7ee9e3200bd55fba9b800018282581d6052e63f22c5107ed776b70f7b92248b02552fd08f3e747bc745099441821a002f9d38ac581c01a7db2a2a897c4a84ca4b75b17281df80cc8607413644d21a9e020da14b73746172666f726765313002581c01c2435381c8362192bce939c002a99ce79c7bb7ba399cc55e2af07da14b73746172666f726765373901581c02f917e4ebe2f3474a713ec76e45e51f1ac72d5b053624d3ee124c12a14a73746172666f7267653201581c07e346cdcb11cff8048cf9ae2166a54c3324cf09b04c7554d6e94391a14b73746172666f726765373301581c0b6f1f1220140053fe1a9e44f4d77c12a5909f599970cd9b65e638e6a14b73746172666f726765343301581c0f28da1e6892acb5973ec68aab4e4718fec8761673e9d725343d97a9a14b73746172666f726765393701581c10ccfab9710c68068f3cd2bc86a96420c97b6d363a68b9232097b86aa14b73746172666f726765383801581c11b6c9e65d8e1e1bd51743a8599bfc8d70e1b1ccebb8902e32538c55a14b73746172666f726765313201581c12df514d7cd52225e39a7fe27ee0652dd2f1bfab05139deadda2a7caa14b73746172666f726765383901581c14deabc3a38365004e31a8a865a425e187fe4776e84c626c2c822344a148373536376130363301581cb2e796da6ef0fc4b427ca94f400691f22c949ed09ddd61592611e015a14b73746172666f726765343201581ce6911f8b6bae62fc20b96e55131bbf189334baab80d07f2964ca3b6da14a73746172666f726765300382581d6052e63f22c5107ed776b70f7b92248b02552fd08f3e747bc7450994411b000000058503a08a021a00030d40031a01ba9424a0f5f6"}'

protocolParametersJSON=$(cardano-cli conway query protocol-parameters)

cardano-cli conway transaction calculate-min-fee --tx-body-file <(echo ${dummyTx}) --protocol-params-file <(echo ${protocolParametersJSON}) --witness-count 1 --reference-script-size 0

Error: "Error in $: key \"extraPraosEntropy\" not found"
```
So the cli complains about the missing `extrapraosEntropy` parameter. To simulate the presence of the `extraPraosEntropy` we can do:
```bash
protocolParametersJSON=$(./cardano-cli conway query protocol-parameters | jq -r ". += {\"extraPraosEntropy\": null}")

cardano-cli conway transaction calculate-min-fee --tx-body-file <(echo ${dummyTx}) --protocol-params-file <(echo ${protocolParametersJSON}) --witness-count 1 --reference-script-size 0

Error: "Error in $: key \"minUTxOValue\" not found"
```
Now its complaining about the missing `minUTxOVallue`

If we also add this with the null value again, the fee calculation works:
```bash
protocolParametersJSON=$(./cardano-cli conway query protocol-parameters | jq -r ". += {\"extraPraosEntropy\": null, \"minUTxOValue\": null}")

cardano-cli conway transaction calculate-min-fee --tx-body-file <(echo ${dummyTx}) --protocol-params-file <(echo ${protocolParametersJSON}) --witness-count 1 --reference-script-size 0

189173 Lovelace
```

Same errors are for the `calculate-min-required-utxo` function.

**Comment by smelc** [comment]
Work happening at https://github.com/IntersectMBO/cardano-cli/commits/smelc/8.22.0.0-backport-write-protocol-parameters-use-ledger-encoding/

I will bring the commits to this PR when I'm done. I need to work on 8.22.0.0 to more easily test that with `cardano-node` `master`.

File: cardano-cli/src/Cardano/CLI/EraBased/Run/Query.hs (hunk 1 above)
Comment (carbolymer) [reply cardano-cli/src/Cardano/CLI/EraBased/Run/Query.hs:189]: @smelc yes, we should only use one encoding, so in this case ledger's.

**Comment by carbolymer** [comment]
@smelc check afterwards with @mkoura if it's not breaking [cardano-node-tests](https://github.com/IntersectMBO/cardano-node-tests) too.

**Comment by smelc** [comment]
@gitmachtl> can you give this PR a new round of testing?

**Comment by gitmachtl** [comment]
> @gitmachtl> can you give this PR a new round of testing?

@smelc yea, will do it over the weekend, thx.

**Comment by gitmachtl** [comment]
> @gitmachtl> can you give this PR a new round of testing?

@smelc looking good. did test the min-fee calculation, min-utxo calculation, made transactions via build-raw and ran the new build-estimate command with the new protocol-parameter version. 👍   but i only tested in conway era. have to redo it also in babbage era.

**Comment by gitmachtl** [comment]
@smelc ok, babbage era also looks good 👍

**Comment by smelc** [comment]
Thanks @gitmachtl for the feedback :pray:

**Review by Jimbo4350 — APPROVED** [review]
LGTM! Feel free to merge as long as @gitmachtl is happy.

**Comment by gitmachtl** [comment]
> LGTM! Feel free to merge as long as @gitmachtl is happy.

@Jimbo4350 i am happy 😄
