### PR TITLE
Make `query pool-state` default to returning information on all pools

### LINKED ISSUE #496: cli 8.16.0.1 returns an empty json for the `query pool-state`  command
Used cardano-cli version:
```console
$ cardano-cli version
cardano-cli 8.16.0.1 - linux-x86_64 - ghc-8.10
git rev 7f7a93d248b380d3dbff8c003a3ad66b6d1c770f
```

Pools are registered on the chain - this is sanchonet in conway era:
```console
$ cardano-cli conway query stake-pools
pool1rdaxrw3722f0x3nx4uam9u9c6dh9qqd2g83r2uyllf53qmmj5uu
pool13lr6wv9m55el9ahscn8qmutc80gq9m5ajgawjstj3v5rqm7fpd9
pool1h722gdd6kx782me0v9zresnds4ajugneq0vl9a0ju7mgvemezdf
pool1enfptmu732hprd524zzcq7mm055gqvw2vz8dg0xnh39xw9czpm2
pool1m840r7thpj9mxhw33hud3g9jkvjvm00wkw89ul8t06nngjewl6m
```

Doing a specific request for a pool-id works:
```console
$ cardano-cli conway query pool-state --stake-pool-id pool1h722gdd6kx782me0v9zresnds4ajugneq0vl9a0ju7mgvemezdf
{
    "bf94a435bab1bc756f2f61443cc26d857b2e227903d9f2f5f2e7b686": {
        "futurePoolParams": null,
        "poolParams": {
            "cost": 500000000,
            "margin": 1.0,
            "metadata": null,
            "owners": [
                "2f5fde105530993a262d744e534847794d477d2cc5a457312b2014b1"
            ],
            "pledge": 1000000000000,
            "publicKey": "bf94a435bab1bc756f2f61443cc26d857b2e227903d9f2f5f2e7b686",
            "relays": [
                {
                    "single host name": {
                        "dnsName": "sanchonet2-node.play.dev.cardano.org",
                        "port": 3001
                    }
                }
            ],
            "rewardAccount": {
                "credential": {
                    "keyHash": "83d27f03b197750ee41b7dca02c806718164b934b0fbfa747349e8f2"
                },
                "network": "Testnet"
            },
            "vrf": "24e3099f2fdf533c6148c33737c54e908795e13979573bf999df8bc74727fbbe"
        },
        "retiring": null
    }
}
```

But leaving the --stake-pool-id parameter out, the default behavior is normally to list all pool-ids. **Its returning an empty json instead**:
```console
$ cardano-cli conway query pool-state
{}
```
------
Added by CarlosLopezDeLara
 
 This query is also failing on Babbage
 
```
➜  ~ cardano-cli query pool-state --mainnet
Command failed: query pool-state  Error: A query from Babbage era was applied to a ledger from a different era: Alonzo
➜  ~ cardano-cli babbage query pool-state --mainnet
Command failed: query pool-state  Error: A query from Babbage era was applied to a ledger from a different era: Alonzo
```

### PR DESCRIPTION
**Pull request by carlhammann**
# Changelog

```yaml
- description: |
    Make `query pool-state` default to returning information on all pools
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
  # - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  # - improvement    # QoL changes e.g. refactoring
  - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

This PR closes #496. I also took the liberty of making the flags of the `pool-state` query a bit more explicit, with an `--all-stake-pools` flag. This is similar to the `stake-snapshot` query.

There's also a remark from @CarlosLopezDeLara on the issue, where he notes that the query doesn't seem to work in Babbage. Before we figure out what's going on there, I propose we proceed with this PR, since it is orthogonal.

# How to trust this PR

Highlight important bits of the PR that will make the review faster. If there are commands the reviewer can run to observe the new behavior, describe them.

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated. See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [ ] Self-reviewed the diff

### CODE REVIEW

File: cardano-cli/src/Cardano/CLI/EraBased/Options/Query.hs [hunk 1]
```diff
@@ -216,7 +216,7 @@ pQueryPoolStateCmd envCli =
       <$> pSocketPath envCli
       <*> pConsensusModeParams
       <*> pNetworkId envCli
-      <*> many (pStakePoolVerificationKeyHash Nothing)
+      <*> pAllStakePoolsOrOnly
```
Comment (smelc) [inline cardano-cli/src/Cardano/CLI/EraBased/Options/Query.hs:219]: Nice job being able to reuse the same logic as another command :+1:

File: cardano-cli/src/Cardano/CLI/EraBased/Run/Query.hs [hunk 2]
```diff
@@ -633,7 +633,11 @@ runQueryPoolStateCmd
 
         beo <- requireEon BabbageEra era
 
-        result <- lift (queryPoolState beo $ Just $ Set.fromList poolIds)
+        let poolFilter = case allOrOnlyPoolIds of
+              All -> Nothing
+              Only poolIds -> Just $ Set.fromList poolIds
+
+        result <- lift (queryPoolState beo poolFilter)
```
Comment (smelc) [inline cardano-cli/src/Cardano/CLI/EraBased/Run/Query.hs:640]: Where did you see that passing `Nothing` means "no-filtering"? Looking up the definition of `QueryPoolState`, it's not documented. (I don't see what other behavior `Nothing` could have, but being curious).

**Comment by smelc** [comment]
LGTM :champagne:

@carlhammann> were you able to test the new "all" behavior on a true node?

**Review by smelc — APPROVED** [review]

File: cardano-cli/src/Cardano/CLI/EraBased/Run/Query.hs (hunk 2 above)
Comment (carlhammann) [reply cardano-cli/src/Cardano/CLI/EraBased/Run/Query.hs:640]: Code diving [in consensus](https://github.com/input-output-hk/ouroboros-consensus/blob/4322b57bf683cd7ac28bc3e3b9fef3fc30fbc0f2/ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Ledger/Query.hs#L333)...

File: cardano-cli/src/Cardano/CLI/EraBased/Options/Query.hs (hunk 1 above)
Comment (carlhammann) [reply cardano-cli/src/Cardano/CLI/EraBased/Options/Query.hs:219]: I think I might extend that logic to some other commands as well in another PR. There's also potential to sharpen it some more, and make it require the `--all_...` flag, or _a positive_ number of keys.

**Comment by carlhammann** [comment]
> @carlhammann> were you able to test the new "all" behavior on a true node?

That I'll do now, but I wanted to open the PR anyway.

File: cardano-cli/src/Cardano/CLI/EraBased/Run/Query.hs (hunk 2 above)
Comment (carbolymer) [reply cardano-cli/src/Cardano/CLI/EraBased/Run/Query.hs:640]: Good job finding that in consensus Carl! We should start adding docs in API for queries arguments to not loose that information.

**Review by carbolymer — APPROVED** [review]
Nice!

**Comment by carlhammann** [comment]
> > @carlhammann> were you able to test the new "all" behavior on a true node?
> 
> That I'll do now, but I wanted to open the PR anyway.

It works, with the `--all-stake-pools-option`. :tada: I'll merge this now.
