### PR TITLE
Fix #311 - Add Cold Committee Key text envelope

### LINKED ISSUE #311: transaction sign complains when signing with cc-cold-keys
```
cardano-cli conway transaction sign \
--testnet-magic 42 \
--tx-body-file example/transactions/authorization-tx.raw \
--signing-key-file example/utxo-keys/payment1.skey \
--signing-key-file example/cc/cold1-cc.skey \
--out-file example/transactions/authorization-tx.signed

Command failed: transaction sign  Error: Error reading signing key: example/cc/cold1-cc.skey: 
TextEnvelope type error:  Expected one of: PaymentSigningKeyByron_ed25519_bip32, 
PaymentSigningKeyShelley_ed25519, PaymentExtendedSigningKeyShelley_ed25519_bip32, 
StakeSigningKeyShelley_ed25519, StakeExtendedSigningKeyShelley_ed25519_bip32, 
StakePoolSigningKey_ed25519, GenesisSigningKey_ed25519, GenesisExtendedSigningKey_ed25519_bip32, GenesisDelegateSigningKey_ed25519, 
GenesisDelegateExtendedSigningKey_ed25519_bip32, GenesisUTxOSigningKey_ed25519, 
DRepSigningKey_ed25519 Actual: ConstitutionalCommitteeColdSigningKey_ed25519
```
This is required to sign transaction that includes 

**hot-key-authorization-certificate**

```
cardano-cli conway governance committee create-hot-key-authorization-certificate \
--cold-verification-key-file cold1-cc.vkey \
--hot-key-file hot1-cc.vkey \
--out-file hot-key1-cc-authorization.cert
```

```
cardano-cli --version
cardano-cli 8.10.0.0 - linux-x86_64 - ghc-9.2
git rev 000ba9c1d59efb2dc9f4ae3e7910dba7787f46cf
```

### PR DESCRIPTION
**Pull request by carbolymer**
# Changelog

```yaml
- description: |
    Add Cold Committee Key text envelope
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
  # - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  # - improvement    # QoL changes e.g. refactoring
   - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

Fixes #311 

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] The change log section in the PR description has been filled in
- [ ] New tests are added if needed and existing tests are updated.  These may include:
  - golden tests
  - property tests
  - round trip tests
  - integration tests
  See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [ ] The version bounds in `.cabal` files are updated
- [ ] CI passes. See note on CI.  The following CI checks are required:
  - [ ] Code is linted with `hlint`.  See `.github/workflows/check-hlint.yml` to get the `hlint` version
  - [ ] Code is formatted with `stylish-haskell`.  See `.github/workflows/stylish-haskell.yml` to get the `stylish-haskell` version
  - [ ] Code builds on Linux, MacOS and Windows for `ghc-8.10.7` and `ghc-9.2.7`
- [ ] The changelog section in the PR is updated to describe the change
- [ ] Self-reviewed the diff

### CODE REVIEW

**Review by Jimbo4350 — APPROVED** [review]
Do we also want to be able to sign with the committee hot key?

File: cardano-cli/test/cardano-cli-golden/Test/Golden/Shelley/TextEnvelope/Tx/Tx.hs [hunk 1]
```diff
@@ -47,3 +47,40 @@ hprop_golden_shelleyTx = propertyOnce . H.moduleWorkspace "tmp" $ \tempDir -> do
   -- Check the newly created files have not deviated from the
   -- golden files
   checkTxCddlFormat referenceTx transactionFile
+
+
+hprop_golden_checkIfConstitutionalCommitteeKeyCanSign :: Property
+hprop_golden_checkIfConstitutionalCommitteeKeyCanSign = propertyOnce . H.moduleWorkspace "tmp" $ \tempDir -> do
+  -- Reference keys
+  let referenceTx = "test/cardano-cli-golden/files/golden/conway/tx"
```
Comment (newhoggy) [inline cardano-cli/test/cardano-cli-golden/Test/Golden/Shelley/TextEnvelope/Tx/Tx.hs]: Can you put this in `test/cardano-cli-golden/files/input/conway/tx` instead?

I'd like to get to the point where only golden files are in the `golden` directory.
