### PR TITLE
Fix legacy genesis creation

### LINKED ISSUE #1262: `cardano-cli legacy genesis create` creates alonzo genesis with too many cost model values
## Description

When using `cardano-cli legacy genesis create` and alonzo genesis spec with 175 PlutusV2 cost model entries, the command used to produce final alonzo genesis with 175 entries. This way it was possible to run `cardano-cli latest query protocol-parameters` in pre-conway eras where 185 entries is not valid configuration.
The `cardano-cli latest genesis create` produced alonzo genesis with 185 PlutusV2 cost model entries, and this cannot be used in pre-conway eras for querying protocol parameters.

Now with cardano-cli 10.11.0.0, both legacy and latest versions of the commands produce alonzo genesis with 185 PlutusV2 cost model entries. As a result, in pre-conway eras, `cardano-cli latest query protocol-parameters` throws

> Command failed: query protocol-parameters
Error: Unexpected exception while processing query:
DecoderFailure (LocalStateQuery HardForkBlock (': * ByronBlock (': * (ShelleyBlock (TPraos StandardCrypto) ShelleyEra) (': * (ShelleyBlock (TPraos StandardCrypto) AllegraEra) (': * (ShelleyBlock (TPraos StandardCrypto) MaryEra) (': * (ShelleyBlock (TPraos StandardCrypto) AlonzoEra) (': * (ShelleyBlock (Praos StandardCrypto) BabbageEra) (': * (ShelleyBlock (Praos StandardCrypto) ConwayEra) ('[] *)))))))) Query (BlockQuery (HardForkBlock (': * ByronBlock (': * (ShelleyBlock (TPraos StandardCrypto) ShelleyEra) (': * (ShelleyBlock (TPraos StandardCrypto) AllegraEra) (': * (ShelleyBlock (TPraos StandardCrypto) MaryEra) (': * (ShelleyBlock (TPraos StandardCrypto) AlonzoEra) (': * (ShelleyBlock (Praos StandardCrypto) BabbageEra) (': * (ShelleyBlock (Praos StandardCrypto) ConwayEra) ('[] *))))))))))) ServerHasAgency (SingQuerying) (DeserialiseFailure 1063 "Expected array with 175 entries, but encoded array has 185 entries.")

This makes it impossible to check current protocol version to verify that the testnet properly progressed e.g. to Alonzo PV6 or Babbage PV8.

## Steps to Reproduce

1.
```
cardano-cli legacy genesis create  \
  --genesis-dir ./shelley  \
  --testnet-magic 42  \
  --gen-genesis-keys 1  \
  --start-time 2025-08-14T14:43:09Z  \
  --gen-utxo-keys 1
```
2. Check that PlutusV2 cost model in `./shelley/genesis.alonzo.json` has 185 entries.

## Additional Context

Tested on node 10.5.1.
Files needed to run the `genesis create`: [shelley.tar.gz](https://github.com/user-attachments/files/21776994/shelley.tar.gz)

### PR DESCRIPTION
**Pull request by Jimbo4350**
# Changelog
Resolves #1262 
```yaml
- description: |
    `cardano-cli legacy genesis create` recently removed the ability to specify the alonzo era and therefore the ability to    
     generate a V2 cost model with 175 (instead of 185) parameters. This PR restores that functionality.
  type:
  - compatible     # the API has changed but is non-breaking
```

# Context

Additional context for the PR goes here. If the PR fixes a particular issue please provide a [link](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword=) to the issue.

# How to trust this PR

Highlight important bits of the PR that will make the review faster. If there are commands the reviewer can run to observe the new behavior, describe them.

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated. See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [ ] Self-reviewed the diff

### CODE REVIEW

File: cardano-cli/src/Cardano/CLI/EraBased/Genesis/Option.hs [hunk 1]
```diff
@@ -187,10 +188,10 @@ pGenesisCreateCardano envCli =
         "JSON file with genesis defaults for conway."
       <*> pNodeConfigTemplate
 
-pGenesisCreate :: Exp.IsEra era => EnvCli -> Parser (GenesisCmds era)
+pGenesisCreate :: forall era. Exp.IsEra era => EnvCli -> Parser (GenesisCmds era)
 pGenesisCreate envCli =
   fmap GenesisCreate $
-    GenesisCreateCmdArgs (convert Exp.useEra)
+    GenesisCreateCmdArgs (toAnyShelleyBasedEra @era Exp.useEra)
```
Comment (carbolymer) [inline cardano-cli/src/Cardano/CLI/EraBased/Genesis/Option.hs]: how about this instead of another matching function?
```suggestion
    GenesisCreateCmdArgs (AnyShelleyBasedEra $ eraToSbe @era Exp.useEra)
```

File: cardano-cli/src/Cardano/CLI/Legacy/Option.hs [hunk 2]
```diff
@@ -378,3 +378,33 @@ pGenesisCmds envCli =
...
+envCliShelleyBasedEra envCli = do
+  AnyCardanoEra era <- envCliAnyCardanoEra envCli
+  case era of
+    ByronEra -> Nothing
+    ShelleyEra -> Just $ AnyShelleyBasedEra ShelleyBasedEraShelley
+    AllegraEra -> Just $ AnyShelleyBasedEra ShelleyBasedEraAllegra
+    MaryEra -> Just $ AnyShelleyBasedEra ShelleyBasedEraMary
+    AlonzoEra -> Just $ AnyShelleyBasedEra ShelleyBasedEraAlonzo
+    BabbageEra -> Just $ AnyShelleyBasedEra ShelleyBasedEraBabbage
+    ConwayEra -> Just $ AnyShelleyBasedEra ShelleyBasedEraConway
```
Comment (carbolymer) [inline cardano-cli/src/Cardano/CLI/Legacy/Option.hs]: Let's try to avoid matching on every era wherever it's possible. It'll mean less places to update for the new era.
```suggestion
  AnyShelleyBasedEra <$> forEraMaybeEon era
```

**Review by carbolymer — APPROVED** [review]

File: cardano-cli/src/Cardano/CLI/Legacy/Option.hs [hunk 3]
```diff
@@ -378,3 +378,33 @@ pGenesisCmds envCli =
...
+    , flag' (AnyShelleyBasedEra ShelleyBasedEraMary) $
+        mconcat [long "mary", Opt.help "Specify the Mary era"]
+    , flag' (AnyShelleyBasedEra ShelleyBasedEraAlonzo) $
+        mconcat [long "alonzo", Opt.help "Specify the Alonzo era"]
+    , flag' (AnyShelleyBasedEra ShelleyBasedEraBabbage) $
+        mconcat [long "babbage", Opt.help "Specify the Babbage era"]
+    , flag' (AnyShelleyBasedEra ShelleyBasedEraConway) $
+        mconcat [long "conway", Opt.help "Specify the Conway era"]
+    ]
+      ++ (pure <$> maybeToList (envCliShelleyBasedEra envCli))
```
Comment (palas) [inline cardano-cli/src/Cardano/CLI/Legacy/Option.hs]:
```suggestion
pShelleyBasedEra :: EnvCli -> Parser AnyShelleyBasedEra
pShelleyBasedEra envCli =
  asum $
    [ shelleyBasedEraFlag era
    | era <- enumFrom minBound
    ]
      ++ (pure <$> maybeToList (envCliShelleyBasedEra envCli))
 where
  shelleyBasedEraFlag :: AnyShelleyBasedEra -> Parser AnyShelleyBasedEra
  shelleyBasedEraFlag era@(AnyShelleyBasedEra sbe) =
    let eraName = show . pretty $ toCardanoEra sbe
     in flag' era $
          mconcat
            [ long $ map toLower eraName
            , Opt.help $ "Specify the " <> eraName <> " era"
            ]
```

We can generalise the era here and then it will be easier to maintain

File: cardano-cli/src/Cardano/CLI/EraBased/Genesis/Run.hs [hunk 4]
```diff
@@ -228,7 +228,8 @@ runGenesisAddrCmd
 --
 
 runGenesisCreateCmd
-  :: GenesisCreateCmdArgs era
+  :: forall era e
+   . GenesisCreateCmdArgs era
```
Comment (palas) [inline cardano-cli/src/Cardano/CLI/EraBased/Genesis/Run.hs]:
```suggestion
  :: GenesisCreateCmdArgs era
```
I think this change is not necessary

**Review by palas — APPROVED** [review]
Looks good, just a couple of suggestions to simplify the code

File: cardano-cli/src/Cardano/CLI/EraBased/Genesis/Option.hs (hunk 1 above)
Comment (Jimbo4350) [reply cardano-cli/src/Cardano/CLI/EraBased/Genesis/Option.hs]:
```
In the use of ‘eraToSbe’
(imported from Cardano.Api.Experimental, but defined in Cardano.Api.Experimental.Era):
Deprecated: "Use 'convert' instead."
```

Comment (Jimbo4350) [reply cardano-cli/src/Cardano/CLI/EraBased/Genesis/Option.hs]: Perhaps we should bring it back.

Comment (carbolymer) [reply cardano-cli/src/Cardano/CLI/EraBased/Genesis/Option.hs]: Or just use `convert`?

**Review by mkoura — APPROVED** [review]
