### PR TITLE
Make genesis creation commands era-sensitive

### LINKED ISSUE #801: New Plutus V2 cost model parameters are mandatory for alonzo genesis spec in map format
## Description

New Plutus V2 cost model parameters are mandatory for alonzo genesis spec in map format. The issue does not occur for parameters in a list.

## Steps to Reproduce

1. Execute
```
babbage genesis create-testnet-data --spec-alonzo ./alonzo-genesis.spec.json --out-dir out
```
Using this alonzo genesis spec file:
[alonzo-genesis.spec.json](https://github.com/user-attachments/files/15956757/alonzo-genesis.spec.json)
This spec file contains only 175 PlutusV2 cost model parameters. After those changes:
* https://github.com/IntersectMBO/plutus/commit/0ce328cae98e7dfe9b88c15523e626745ad7aaef
* https://github.com/IntersectMBO/cardano-cli/commit/3aaf840c358b3e3147bf4e335ba40d3ada9afcd7#diff-af5654689b4e6a082369ffd7f0967e7d703e09c89a357fe42f9fd31498b4e3c0R189

Plutus V2 cost model has 185 parameters.  

## Expected result
The genesis gets created with old list of parameters.

## Actual result
`cardano-cli` reports and error:
```
Command failed: genesis create-testnet-data  Error: Error while decoding Shelley genesis at: ./alonzo-genesis.spec.json Error: Error in $.costModels: Unrecognized cost model parameter name: "integerToByteString-cpu-arguments-c0"
```

### PR DESCRIPTION
**Pull request by carbolymer**
# Changelog

```yaml
- description: |
    Make `genesis`: `create`, `create-staked` and `create-cardano` commands accept optional era parameters.
# uncomment types applicable to the change:
  type:
   - feature        # introduces a new feature
  # - breaking       # the API has changed in a breaking way
   - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  # - refactoring    # QoL changes
  # - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

Make `genesis`: `create`, `create-staked` and `create-cardano` commands accept optional era parameters. This is needed for decoding of Alonzo genesis. This PR requires changes from: https://github.com/IntersectMBO/cardano-api/pull/564

Fixes: https://github.com/IntersectMBO/cardano-cli/issues/801

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated. See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [ ] Self-reviewed the diff

### CODE REVIEW

File: cardano-cli/src/Cardano/CLI/EraBased/Commands/Genesis.hs [hunk 1]
```diff
@@ -40,8 +40,9 @@ data GenesisCmds era
   | GenesisHashFile !GenesisFile
   deriving Show
 
-data GenesisCreateCmdArgs = GenesisCreateCmdArgs
-  { keyOutputFormat :: !KeyOutputFormat
+data GenesisCreateCmdArgs era = GenesisCreateCmdArgs
+  { eon :: !(CardanoEra era)
```
Comment (Jimbo4350) [inline cardano-cli/src/Cardano/CLI/EraBased/Commands/Genesis.hs]: This should be `ShelleyBasedEra era`

**Comment by smelc** [comment]
Looking good so far :+1:

**Comment by palas** [comment]
Backup: https://github.com/IntersectMBO/cardano-cli/tree/backup/mgalazyn/fix/make-plutus-v2-cost-model-era-dependent

**Comment by palas** [comment]
FYI: I have rebased your branch because we have done changes to the formatting. I have made a copy of the unrebased branch that you can find in my previous comment in this PR.

File: cabal.project [hunk 2]
```diff
@@ -57,3 +57,12 @@ write-ghc-environment-files: always
 -- IMPORTANT
 -- Do NOT add more source-repository-package stanzas here unless they are strictly
 -- temporary! Please read the section in CONTRIBUTING about updating dependencies.
+
+source-repository-package
```
Comment (carbolymer) [inline cabal.project]: * [ ] Remove SRP

File: cardano-cli/src/Cardano/CLI/EraBased/Run/Genesis/Common.hs [hunk 3]
```diff
@@ -0,0 +1,136 @@
...
+{-# LANGUAGE FlexibleInstances #-}
+{-# LANGUAGE GADTs #-}
+{-# LANGUAGE RankNTypes #-}
+{-# LANGUAGE ScopedTypeVariables #-}
+{-# LANGUAGE TypeApplications #-}
+
+module Cardano.CLI.EraBased.Run.Genesis.Common
+  ( decodeShelleyGenesisFile
+  , decodeAlonzoGenesisFile
+  , decodeConwayGenesisFile
```
Comment (carbolymer) [inline cardano-cli/src/Cardano/CLI/EraBased/Run/Genesis/Common.hs:14]: Those are new functions, the other ones were moved as-is.

**Review by smelc — APPROVED** [review]

**Review by Jimbo4350 — APPROVED** [review]
LGTM!
