### PR TITLE
create-testnet-data: fix that treasury could be unexpectedly negative

### LINKED ISSUE #643: create-testnet-data: treasury can be unexpectedly negative
`create-testnet-data` fails when the total supply is greatly superior to the delegated-supply, as in:

```shell
> cabal run cardano-cli -- conway genesis create-testnet-data --out-dir create_testnet_out --stake-delegators 3 --pools 3 --utxo-keys 3 --drep-keys 3 --testnet-magic 42 --total-supply 1000000000000 --delegated-supply 1000000001
Command failed: genesis create-testnet-data  Error: Provided delegated supply value results in negative initial funds. Decrease delegated amount by 98899999998 or increase total supply by it.
```

This was originally reported by @carbolymer [here](https://github.com/IntersectMBO/cardano-node/pull/5639/files#r1512199219).

### PR DESCRIPTION
**Pull request by smelc**
# Changelog

```yaml
- description: |
    create-testnet-data: fix that treasury could be unexpectedly negative
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
  - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  - improvement    # QoL changes e.g. refactoring
  - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

Fixes https://github.com/IntersectMBO/cardano-cli/issues/643

# How to trust this PR

I wanted to test that `cabal test cardano-testnet` passed on `cardano-node`,  using this version of `cardano-cli`; but it's not easy to do right now. Still I think this is safe.

# Checklist

- [X] Commit sequence broadly makes sense and commits have useful messages
- [X] New tests are added if needed and existing tests are updated. See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [X] Self-reviewed the diff

### CODE REVIEW

**Review by carbolymer — APPROVED** [review]

File: cardano-cli/src/Cardano/CLI/Types/Errors/GenesisCmdError.hs [hunk 1]
```diff
@@ -101,5 +101,7 @@ instance Error GenesisCmdError where
       " Error: " <> pretty e
     GenesisCmdFileInputDecodeError ide ->
       "Error occured while decoding a file: " <> pshow ide
-    GenesisCmdNegativeInitialFunds underflow ->
-      "Provided delegated supply value results in negative initial funds. Decrease delegated amount by " <> pretty ((-1) * underflow) <> " or increase total supply by it."
+    GenesisCmdDelegatedSupplyExceedsTotalSupply delegated total ->
+      "Provided delegated supply is " <> pretty delegated <> ", which is greater than the specified total supply: " <> pretty total <> "." <>
+      "This is incorrect: the delegated supply should be less or equal to the total supply." <>
+      " Note that the total supply can either come from --total-supply or from the default template. Please fix what you use."
```
Comment (Jimbo4350) [inline cardano-cli/src/Cardano/CLI/Types/Errors/GenesisCmdError.hs:107]: Which one takes precedent? The template or the cli parser?

File: cardano-cli/src/Cardano/CLI/EraBased/Run/CreateTestnetData.hs [hunk 2]
```diff
@@ -603,18 +602,18 @@ updateOutputTemplate
...
   where
-    getCoinForDistribution :: Integer -> m Natural
-    getCoinForDistribution inputCoin = do
-      let value = inputCoin - subtrahendForTreasury
-      when (value < 0) $ throwError $ GenesisCmdNegativeInitialFunds value
-      pure $ fromInteger value
+    nonDelegCoin = getCoinForDistribution nonDelegCoinRaw
+    delegCoin = getCoinForDistribution delegCoinRaw
+
+    getCoinForDistribution :: Integer -> Natural
```
Comment (Jimbo4350) [inline cardano-cli/src/Cardano/CLI/EraBased/Run/CreateTestnetData.hs:608]: Hm. I don't like these hidden calculations. It is always better to be explicit.

**Review by Jimbo4350 — COMMENTED** [review]
:+1:

File: cardano-cli/src/Cardano/CLI/EraBased/Run/CreateTestnetData.hs (hunk 2 above)
Comment (smelc) [reply cardano-cli/src/Cardano/CLI/EraBased/Run/CreateTestnetData.hs:608]: @Jimbo4350> note that it was like this before in `create-staked`.

File: cardano-cli/src/Cardano/CLI/Types/Errors/GenesisCmdError.hs (hunk 1 above)
Comment (smelc) [reply cardano-cli/src/Cardano/CLI/Types/Errors/GenesisCmdError.hs:107]: @Jimbo4350> the template takes precedence :+1:
