### PR TITLE
Fix delegating to always-no-confidence

### LINKED ISSUE #402: vote delegation to --always-no-confidence is captured as --always-abstain
vote delegation to --always-no-confidence is captured as --always-abstain

### Steps to reproduce: 
 
Generate a vote delegation certificate to --always-no-confidence : 

```
  $CARDANO_CLI conway stake-address vote-delegation-certificate \
    --stake-verification-key-file "${UTXO_DIR}/stake${i}.vkey" \
    --always-no-confidence \
    --out-file "${TRANSACTIONS_DIR}/drep-deleg${i}.cert"
```

Find the CBOR 

```
cat example/transactions/drep-deleg1.cert
{
    "type": "CertificateShelley",
    "description": "Stake Address Delegation Certificate",
    "cborHex": "83098200581c3dc96f0f04fdae3ad3c74182dfe0f720ba06c1ed2b15b78761d712908102"
}
```

decode on cbor.me or similar tool

`[9, [0, h'3DC96F0F04FDAE3AD3C74182DFE0F720BA06C1ED2B15B78761D71290'], [2]]`

it records `[2]`; but the cddl tells us that no confidence should be 3 

https://github.com/input-output-hk/cardano-ledger/blob/ad3f40abc55184ffd494e2239c43eec5dc8e423d/eras/conway/test-suite/cddl-files/conway.cddl#L326C1-L331C4

When submitting the certificate it is captured by ledger state as delegated to `--always-abstain` [2], and not to `--always-no-confidence` [3]

```
              "keyHash-3dc96f0f04fdae3ad3c74182dfe0f720ba06c1ed2b15b78761d71290": {
                "reward": 24703004483,
                "deposit": 0,
                "ptr": [],
                "spool": "3d5e0af9fb0a82c2256faa9eb4f9db6d7b2f0af843b9e3c3dcbbfea6",
                "drep": {
                  "tag": "DRepAlwaysAbstain"
                }
              },
```
### Expected behavior 

to delegate to --always-no-confidence  default Drep. 

### version 
```
cardano-cli --version
cardano-cli 8.12.0.0 - linux-x86_64 - ghc-8.10
git rev f1ce770834bf7150ca29cb647065c9e62d39be1a
```

### 

This seems to be the source of the problem https://github.com/input-output-hk/cardano-cli/blob/9293cdb546cd654aaa6d5f4f49511921eb5012d7/cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs#L3038

### PR DESCRIPTION
**Pull request by CarlosLopezDeLara**
# Changelog

```yaml
- description: |
   - Fix delegating to always no confidence default DRep
   - Add golden tests for stake address vote delegation certificates
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
  # - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  # - improvement    # QoL changes e.g. refactoring
   - bugfix         # fixes a defect
   - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

Resolves https://github.com/input-output-hk/cardano-cli/issues/402
Now it carries the corresponding [3] (it was 2)

`[9, [0, h'EF1785CF18928F8353C90E76B7A8FC60855472D31A0EA1C1C774AB01'], [3]]`

**tests pending**

# How to trust this PR

```
              "keyHash-ef1785cf18928f8353c90e76b7a8fc60855472d31a0ea1c1c774ab01": {
                "reward": 310415375988,
                "deposit": 0,
                "ptr": [],
                "spool": "c27cf021914a2b3bcb286d3d741979083422378c577fe757702b6988",
                "drep": {
                  "tag": "DRepAlwaysNoConfidence"
                }
              }
            },
```
Before it was 

```
              "keyHash-3dc96f0f04fdae3ad3c74182dfe0f720ba06c1ed2b15b78761d71290": {
                "reward": 24703004483,
                "deposit": 0,
                "ptr": [],
                "spool": "3d5e0af9fb0a82c2256faa9eb4f9db6d7b2f0af843b9e3c3dcbbfea6",
                "drep": {
                  "tag": "DRepAlwaysAbstain"
                }
              },
```

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [x] New tests are added if needed and existing tests are updated. See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [x] Self-reviewed the diff

### CODE REVIEW

**Review by carbolymer — APPROVED** [review]

File: cardano-cli/test/cardano-cli-golden/Test/Golden/Governance/StakeAddress.hs [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+    delegGold <- H.note "test/cardano-cli-golden/files/golden/governance/stakeaddress/noConfidenceDeleg.cert"
+
+    void $ execCardanoCLI
+      [ "conway", "stake-address", "vote-delegation-certificate"
+      , "--stake-verification-key-file", vkeyFile
+      , "--always-no-confidence"
+      , "--out-file", delegFile
+      ]
+
+    H.diffFileVsGoldenFile delegFile delegGold
```
Comment (carbolymer) [inline cardano-cli/test/cardano-cli-golden/Test/Golden/Governance/StakeAddress.hs:27]: can we check if the output file contains the vote we desire here?

Comment (CarlosLopezDeLara) [reply cardano-cli/test/cardano-cli-golden/Test/Golden/Governance/StakeAddress.hs:27]: We could parse the cbor on the envelope and make sure it ends with 8103. But the test as is will fail if it doesn't.

Comment (carlhammann) [reply cardano-cli/test/cardano-cli-golden/Test/Golden/Governance/StakeAddress.hs:27]: I think it's good to test the whole file, as done here. Testing that the CBOR ends in some specific magic sequence seems too obscure to me. In fact, all of the tests in this module have completely fixed inputs, so there should be no problem in checking the complete outputs.

**Review by carlhammann — APPROVED** [review]
:tada:

File: cardano-cli/test/cardano-cli-golden/files/golden/governance/stakeaddress/alwaysAbstainDeleg.cert [hunk 2]
```diff
@@ -0,0 +1,5 @@
+{
+    "type": "CertificateShelley",
+    "description": "Stake Address Delegation Certificate",
```
Comment (Jimbo4350) [inline cardano-cli/test/cardano-cli-golden/files/golden/governance/stakeaddress/alwaysAbstainDeleg.cert]: Not for this PR but should be update the description to read something like "Stake Address Vote Delegation Certificate"?

**Review by Jimbo4350 — APPROVED** [review]

**Comment by Jimbo4350** [comment]
Congrats on your first Haskell PR! :tada:

File: cardano-cli/test/cardano-cli-golden/files/golden/governance/stakeaddress/alwaysAbstainDeleg.cert (hunk 2 above)
Comment (CarlosLopezDeLara) [reply cardano-cli/test/cardano-cli-golden/files/golden/governance/stakeaddress/alwaysAbstainDeleg.cert]: Addressed on the latest commit. I recovered the descriptions we had when the command was under Dreps.hs

**Review by disassembler — APPROVED** [review]
