### PR TITLE
create-testnet-data: fix computation of not-delegated amount

### LINKED ISSUE #631: create-testnet-data: wrong supply/total-supply interaction
From @mgmeier [here on Slack](https://input-output-rnd.slack.com/archives/G011N23CEAE/p1709123044922159?thread_ts=1709122860.910209&cid=G011N23CEAE):

> In Cardano.CLI.EraBased.Run.CreateTestnetData.updateOutputTemplate:

    delegCoinRaw, nonDelegCoinRaw :: Integer
    delegCoinRaw = case mDelegatedSupply of Nothing -> 0; Just (Lovelace amountDeleg) -> totalSupply - amountDeleg
    nonDelegCoinRaw = totalSupply - delegCoinRaw
this seems to be doing the wrong thing. I.e., subtracting the amountDeleg from the total supply does not give you the delegated coin, rather the non-delegated coin. So I suspect, the values might end up being reversed here.

> Comparing with the behaviour of create-staked:

Cardano.CLI.EraBased.Run.CreateTestnetData.updateOutputTemplate:
    maximumLovelaceSupply :: Word64
    maximumLovelaceSupply = sgMaxLovelaceSupply template

    totalSupply :: Integral a => a
    -- if --total-supply is not specified, supply comes from the template passed to this function:
    totalSupply = fromIntegral $ maybe maximumLovelaceSupply unLovelace mTotalSupply

> Cardano.CLI.EraBased.Run.Genesis.updateOutputTemplate:

    maximumLovelaceSupply :: Word64
    maximumLovelaceSupply = sgMaxLovelaceSupply template

    nonDelegCoin, delegCoin :: Integer
    -- if --supply is not specified, non delegated supply comes from the template passed to this function:
    nonDelegCoin = fromIntegral (maybe maximumLovelaceSupply unLovelace mAmountNonDeleg)

> This seems be  incosistent wrt. the template field sgMaxLovelaceSupply. In 1., it serves as base for the total supply - in 2., as base for the nonDelegCoin.
Isn't the template field semantics (e.g. from genesis.spec.json) meant to be consistent across commands - namely create-staked and create-testnet-data?

### PR DESCRIPTION
**Pull request by smelc**
# Changelog

```yaml
- description: |
    create-testnet-data: fixes that amount of delegated coins was incorrect
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
  - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  # - improvement    # QoL changes e.g. refactoring
  - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

Fixes https://github.com/IntersectMBO/cardano-cli/issues/631

# How to trust this PR

1. Run the new test (`cabal test cardano-cli-golden --test-options '-p "/golden create testnet data deleg non deleg/"'`) before the fix, witness the test fails
2. Run the test on the head of this PR. Enjoy the passing test.
3. Tested on `cardano-node` locally
4. Tested CI on `cardano-node`: https://github.com/IntersectMBO/cardano-node/pull/5712

# Checklist

- [X] Commit sequence broadly makes sense and commits have useful messages
- [X] New tests are added if needed and existing tests are updated. See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [X] Self-reviewed the diff

### CODE REVIEW

File: cardano-cli/test/cardano-cli-golden/Test/Golden/CreateTestnetData.hs [hunk 1]
```diff
@@ -134,3 +137,40 @@ hprop_golden_create_testnet_data_transient_stake_delegators =
...
+
+    void $ execCardanoCLI
+      [ "conway", "genesis", "create-testnet-data"
+      , "--utxo-keys", "1"
+      , "--total-supply", show totalSupply
+      , "--delegated-supply", show delegatedSupply
+      , "--out-dir", outputDir]
+
+    bs <- liftIO $ LBS.readFile $ outputDir </> "genesis.json"
+    genesis :: ShelleyGenesis StandardCrypto <- Aeson.throwDecode bs
```
Comment (carbolymer) [inline cardano-cli/test/cardano-cli-golden/Test/Golden/CreateTestnetData.hs]: You can use here https://hackage.haskell.org/package/hedgehog-extras-0.6.1.0/docs/Hedgehog-Extras-Test-File.html#v:readJsonFileOk

File: cardano-cli/src/Cardano/CLI/EraBased/Run/CreateTestnetData.hs [hunk 2]
```diff
@@ -622,7 +621,8 @@ updateOutputTemplate
     totalSupply = fromIntegral $ maybe maximumLovelaceSupply unLovelace mTotalSupply
 
     delegCoinRaw, nonDelegCoinRaw :: Integer
-    delegCoinRaw = case mDelegatedSupply of Nothing -> 0; Just (Lovelace amountDeleg) -> totalSupply - amountDeleg
+    delegCoinRaw = maybe 0 unLovelace mDelegatedSupply
```
Comment (carbolymer) [inline cardano-cli/src/Cardano/CLI/EraBased/Run/CreateTestnetData.hs:624]: 👍🏻

File: cardano-cli/test/cardano-cli-golden/Test/Golden/CreateTestnetData.hs [hunk 3]
```diff
@@ -134,3 +137,40 @@ hprop_golden_create_testnet_data_transient_stake_delegators =
...
+    -- Because we don't test this elsewhere in this file:
+    (L.sgMaxLovelaceSupply genesis) H.=== (fromIntegral totalSupply)
+
+    let initialFunds = ListMap.toList $ L.sgInitialFunds genesis
+
+    (length initialFunds) H.=== 1
+    let L.Coin onlyHolderCoin = snd $ initialFunds !! 0
+
+    -- The check below may seem weird, but we cannot do a very precise check
+    -- on balances, because of the treasury "stealing" some of the money.
```
Comment (carbolymer) [inline cardano-cli/test/cardano-cli-golden/Test/Golden/CreateTestnetData.hs:175]: What do you mean by that? I thought that treasury starts empty, and gets filled with time from reserves.

File: cardano-cli/test/cardano-cli-golden/Test/Golden/CreateTestnetData.hs [hunk 4]
```diff
@@ -134,3 +137,40 @@ hprop_golden_create_testnet_data_transient_stake_delegators =
...
+    -- Nevertheless, this check catches a confusion between delegated and
+    -- non-delegated coins, by virtue of --delegated-supply being a fourth
+    -- of --total-supply above.
+    -- https://github.com/IntersectMBO/cardano-cli/issues/631
+
+    H.assert $ fromIntegral onlyHolderCoin > totalSupply `div` 2
```
Comment (carbolymer) [inline cardano-cli/test/cardano-cli-golden/Test/Golden/CreateTestnetData.hs]: Can you replace it with `assertWith`? `assertWith` logs the value on failure.

**Review by carbolymer — APPROVED** [review]

File: cardano-cli/test/cardano-cli-golden/Test/Golden/CreateTestnetData.hs (hunk 3 above)
Comment (smelc) [reply cardano-cli/test/cardano-cli-golden/Test/Golden/CreateTestnetData.hs:175]: @carbolymer> I mean that: https://github.com/IntersectMBO/cardano-cli/blob/main/cardano-cli/src/Cardano/CLI/EraBased/Run/CreateTestnetData.hs#L608

File: cardano-cli/test/cardano-cli-golden/Test/Golden/CreateTestnetData.hs (hunk 4 above)
Comment (smelc) [reply cardano-cli/test/cardano-cli-golden/Test/Golden/CreateTestnetData.hs]: Done :+1: Thanks, I didn't know about `assertWith` :pray:

File: cardano-cli/test/cardano-cli-golden/Test/Golden/CreateTestnetData.hs (hunk 1 above)
Comment (smelc) [reply cardano-cli/test/cardano-cli-golden/Test/Golden/CreateTestnetData.hs]: Done and learnt about `readJsonFileOk` :+1:

File: cardano-cli/test/cardano-cli-golden/Test/Golden/CreateTestnetData.hs [hunk 5]
```diff
@@ -143,3 +143,39 @@ hprop_golden_create_testnet_data_transient_stake_delegators =
...
     -- that generates strictly more stuff.
+
+-- Execute this test with:
+-- @cabal test cardano-cli-golden --test-options '-p "/golden create testnet data deleg non deleg/"'@
+hprop_golden_create_testnet_data_deleg_non_deleg :: Property
+hprop_golden_create_testnet_data_deleg_non_deleg =
+  propertyOnce $ moduleWorkspace "tmp" $ \tempDir -> do
+
+    let outputDir = tempDir </> "out"
+        totalSupply :: Int = 2000000000000 -- 2*10^12
```
Comment (Jimbo4350) [inline cardano-cli/test/cardano-cli-golden/Test/Golden/CreateTestnetData.hs:154]: We need to start using `NumericUnderscores` more

File: cardano-cli/test/cardano-cli-golden/Test/Golden/CreateTestnetData.hs [hunk 6]
```diff
@@ -143,3 +143,39 @@ hprop_golden_create_testnet_data_transient_stake_delegators =
...
+      , "--out-dir", outputDir]
+
+    genesis :: ShelleyGenesis StandardCrypto <- H.readJsonFileOk $ outputDir </> "genesis.json"
+
+    -- Because we don't test this elsewhere in this file:
+    (L.sgMaxLovelaceSupply genesis) H.=== (fromIntegral totalSupply)
+
+    let initialFunds = ListMap.toList $ L.sgInitialFunds genesis
+
+    (length initialFunds) H.=== 1
```
Comment (Jimbo4350) [inline cardano-cli/test/cardano-cli-golden/Test/Golden/CreateTestnetData.hs:171]: Some commentary would be useful here. Eg "This checks that there is actually only one funded address" 
We can also introduce a variable e.g `let fundedAddresses = 1` to make this even more clear.

File: cardano-cli/test/cardano-cli-golden/Test/Golden/CreateTestnetData.hs [hunk 7]
```diff
@@ -143,3 +143,39 @@ hprop_golden_create_testnet_data_transient_stake_delegators =
...
+    let L.Coin onlyHolderCoin = snd $ initialFunds !! 0
+
+    -- The check below may seem weird, but we cannot do a very precise check
+    -- on balances, because of the treasury "stealing" some of the money.
+    -- Nevertheless, this check catches a confusion between delegated and
+    -- non-delegated coins, by virtue of --delegated-supply being a fourth
```
Comment (Jimbo4350) [inline cardano-cli/test/cardano-cli-golden/Test/Golden/CreateTestnetData.hs:177]: This comment needs to be updated as [https://github.com/IntersectMBO/cardano-cli/issues/631](https://github.com/IntersectMBO/cardano-cli/issues/631) is closed

**Review by Jimbo4350 — COMMENTED** [review]
:+1:

File: cardano-cli/test/cardano-cli-golden/Test/Golden/CreateTestnetData.hs (hunk 5 above)
Comment (smelc) [reply cardano-cli/test/cardano-cli-golden/Test/Golden/CreateTestnetData.hs:154]: Actually we do now for this file on `main` :tada:
